website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
import re
from . import db
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    if request.method == 'POST':
        current_password = request.form.get('currentPassword')
        new_password = request.form.get('newPassword')
        confirm_password = request.form.get('confirmPassword')

        user = User.query.filter_by(email=current_user.email).first()
        if user:

            if len(new_password) < 7:
                flash('Password must be at least 7 characters.', category='error')
            elif not re.search('[a-z]', new_password):
                flash('Password must contain at least one lowercase letter.', category='error')
            elif not re.search('[A-Z]', new_password):
                flash('Password must contain at least one uppercase letter.', category='error')
            elif not re.search('[0-9]', new_password):
                flash('Password must contain at least one number.', category='error')
            elif not re.search("[\W]", new_password):
                flash('Password must contain at least one special character.', category='error')
            else:
                if check_password_hash(user.password, current_password):
                    if new_password == confirm_password:
                        user.password = generate_password_hash(new_password, method='sha256')
                        db.session.commit()
                        flash('Password changed successfully!', category='success')
                        return redirect(url_for('views.home'))
                    else:
                        flash('Passwords don\'t match.', category='error')
                else:
                    flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("change_password.html", user=current_user)


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        elif not re.search('[a-z]', password1):
            flash('Password must contain at least one lowercase letter.', category='error')
        elif not re.search('[A-Z]', password1):
            flash('Password must contain at least one uppercase letter.', category='error')
        elif not re.search('[0-9]', password1):
            flash('Password must contain at least one number.', category='error')
        elif not re.search("[\W]", password1):
            flash('Password must contain at least one special character.', category='error')
        else:
            # add user to database
            new_user = User(email=email, first_name=first_name,
                            password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)


@auth.route('/forgot-password', methods=['GET', 'POST'])
def forgot_password():
    if request.method == 'POST':
        email = request.form.get('email')
        new_password = request.form.get('newPassword')
        confirm_password = request.form.get('confirmPassword')
        user = User.query.filter_by(email=email).first()
        print(user)
        if user:
            flash('Email exists.', category='success')
            if len(new_password) < 7:
                flash('Password must be at least 7 characters.', category='error')
            elif not re.search('[a-z]', new_password):
                flash('Password must contain at least one lowercase letter.', category='error')
            elif not re.search('[A-Z]', new_password):
                flash('Password must contain at least one uppercase letter.', category='error')
            elif not re.search('[0-9]', new_password):
                flash('Password must contain at least one number.', category='error')
            elif not re.search("[\W]", new_password):
                flash('Password must contain at least one special character.', category='error')
            else:
                if new_password == confirm_password:
                    user.password = generate_password_hash(new_password, method='sha256')
                    db.session.commit()
                    flash('Password changed successfully!', category='success')
                    return redirect(url_for('auth.login'))
                else:
                    flash('Passwords don\'t match.', category='error')
        else:
            flash('Email does not exist.', category='error')
            return redirect(url_for('auth.login'))

    return render_template("forgot_password.html", user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
    >
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="/">Home</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            <a class="nav-item nav-link" id="change_password" href="/change-password">Change Password</a>
            {% else %}
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
            <a class="nav-item nav-link" id="forgot_password" href="/forgot-password">Forgot Password</a>
            {% endif %}
        </div>
    </div>
</nav>
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %} {% for category, message in messages %}
        {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}
<div class="container">
    {% block content %}{% endblock %}
</div>

<script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
></script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
></script>
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
></script>
<script type="text/javascript"   src="{{ url_for('static',filename='index.js') }}">

</script>
</body>
</html>

website/templates/change_password.html
{% extends "base.html" %}
{% block title %}Change Password{% endblock %}
{% block content %}
   <form method="POST" action="{{ url_for('auth.change_password') }}">
  <h3 align="center">Change Password</h3>
       <div  class="form-group">
      <label for="currentPassword">Current Password</label>
      <input class="form-control" type="password" id="currentPassword" name="currentPassword" required>
    </div>
    <div class="form-group">
      <label for="newPassword">New Password</label>
      <input class="form-control" type="password" id="newPassword" name="newPassword" required>
    </div>
    <div class="form-group">
      <label for="confirmPassword">Confirm New Password</label>
      <input class="form-control" type="password" id="confirmPassword" name="confirmPassword" required>
    </div>
      <br />
       <button type="submit" class="btn btn-primary" value="Change Password">Change Password</button>
   </form>
{% endblock %}

website/templates/forgot_password.html
{% extends "base.html" %}
{% block title %}Change Password{% endblock %}
{% block content %}
   <form method="POST" action="{{ url_for('auth.forgot_password') }}">
  <h3 align="center">Forgot Password</h3>
    <div class="form-group">
      <label for="email">Email</label>
      <input class="form-control" type="email" id="email" name="email" required>
    </div>
    <div class="form-group">
      <label for="newPassword">New Password</label>
      <input class="form-control" type="password" id="newPassword" name="newPassword" required>
    </div>
    <div class="form-group">
      <label for="confirmPassword">Confirm New Password</label>
      <input class="form-control" type="password" id="confirmPassword" name="confirmPassword" required>
    </div>
      <br />
       <button type="submit" class="btn btn-primary" value="Change Password">Change Password</button>
   </form>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">
    {{ note.data }}
    <button type="button" class="close" onClick="deleteNote({{ note.id }})">
      <span aria-hidden="true">&times;</span>
    </button>
  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea name="note" id="note" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form>
{% endblock %}h

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}